name: publish-latest
on: 
  push:
    branches:
      - master
jobs:
  publish-pdf:
    name: Publish latest pdf
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository 
        uses: actions/checkout@v2
        with:
          path: '${{ github.workspace }}/taoe3'

      - name: Compile pdf
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: 'taoe3'
          root_file: 'main.tex'
          latexmk_shell_escape: true

      - name: Checkout gh_pages branch
        uses: actions/checkout@v2
        with:
          path: '${{ github.workspace }}/gh_pages'
          ssh-key: "${{ secrets.COMMIT_KEY }}"
          ref: 'gh_pages'

      - name: Upload to GH Pages
        run: |
          mv ${{ github.workspace }}/taoe3/main.pdf ${{ github.workspace }}/gh_pages/data/taoe3-solutions.pdf
          cd ${{ github.workspace }}/gh_pages
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add data/taoe3-solutions.pdf
          git commit -m "Publish solutions from $GITHUB_SHA"
          git push origin gh_pages
